// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn-RzswDGyckTJ0bqq27_ufzgVqVALIng',
    appId: '1:874591227885:web:be783c4a5ade7a7195a1e4',
    messagingSenderId: '874591227885',
    projectId: 'pawlse',
    authDomain: 'pawlse.firebaseapp.com',
    storageBucket: 'pawlse.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jb6cboRBdEa3FtJtaeYsbu-5_7xDH-Q',
    appId: '1:874591227885:android:339eb34e5968a65a95a1e4',
    messagingSenderId: '874591227885',
    projectId: 'pawlse',
    storageBucket: 'pawlse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmC92rVome3MRVnmKW_bo0TJpJNl-i3eo',
    appId: '1:874591227885:ios:0d18af26138cd3bc95a1e4',
    messagingSenderId: '874591227885',
    projectId: 'pawlse',
    storageBucket: 'pawlse.appspot.com',
    iosBundleId: 'com.example.pawlse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmC92rVome3MRVnmKW_bo0TJpJNl-i3eo',
    appId: '1:874591227885:ios:01fe4c6bc60f7b3895a1e4',
    messagingSenderId: '874591227885',
    projectId: 'pawlse',
    storageBucket: 'pawlse.appspot.com',
    iosBundleId: 'com.example.pawlse.RunnerTests',
  );
}
